export default {
	POST_EVENT_REQUEST: 'POST_EVENT_REQUEST',
	POST_EVENT_SUCCESS: 'POST_EVENT_SUCCESS',

	FETCH_EVENTS_REQUEST: 'FETCH_EVENTS_REQUEST',
	FETCH_EVENTS_SUCCESS: 'FETCH_EVENTS_SUCCESS',

	NEXT_MONTH_CLICKED: 'NEXT_MONTH_CLICKED',
	PREV_MONTH_CLICKED: 'PREV_MONTH_CLICKED'
};