export default {
	POST_EVENT_REQUEST: 'POST_EVENT_REQUEST',
	POST_EVENT_SUCCESS: 'POST_EVENT_SUCCESS',

	FETCH_EVENTS_REQUEST: 'FETCH_EVENTS_REQUEST',
	FETCH_EVENTS_SUCCESS: 'FETCH_EVENTS_SUCCESS',

	GO_TO_DATE: 'GO_TO_DATE'
};